apiVersion: apps/v1
kind: Deployment
metadata:
  name: end-to-end-deploy
spec:
  selector:
    matchLabels:
      app: end-to-end
  template:
    metadata:
      labels:
        app: end-to-end
    spec:
      containers:
        - name: end-to-end
          image: donpk/end-to-end
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
